# -*- coding: utf-8 -*-
"""WorksShopBS2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1L1Lfc-h2yGpJ85GKwKe0NWF5yWV6_7jg
"""

import requests
import pandas as pd
from bs4 import BeautifulSoup

url = "https://quotes.toscrape.com/"
response = requests.get(url, timeout=20)
response.encoding = "utf-8"
soup = BeautifulSoup(response.text, "html.parser")

rows = []

for item in soup.select(".quote"):   # container

    text_el = item.select_one(".text")
    author_el = item.select_one(".author")
    tags_el = item.select(".tag")   # meerdere tags

    text = text_el.get_text(strip=True) if text_el else None
    author = author_el.get_text(strip=True) if author_el else None
    tags = ", ".join([tag.get_text(strip=True) for tag in tags_el]) if tags_el else None

    rows.append({
        "quote": text,
        "author": author,
        "tags": tags
    })

df = pd.DataFrame(rows)
df

df.to_csv("verify_output.csv", index=False)
print(f"Rows: {len(df)}  |  Columns: {list(df.columns)}")
df

# --- Installeer Supabase client ---
!pip install -q supabase requests beautifulsoup4 pandas

# --- Import libraries ---
import requests
from bs4 import BeautifulSoup
import pandas as pd
from supabase import create_client
from datetime import datetime

# --- Supabase connectie ---
SUPABASE_URL = "https://djrnipewkwovxqfeqcah.supabase.co"   # je project URL
SUPABASE_KEY = "sb_publishable_6LaPd7x0_y8oFGt_kS9jsA_T3Ioe2l2"  # je anon/public key

supabase = create_client(SUPABASE_URL, SUPABASE_KEY)

# --- Scrape quotes ---
url = "http://quotes.toscrape.com/page/1/"
rows = []

while url:
    response = requests.get(url, timeout=20)
    soup = BeautifulSoup(response.text, "html.parser")
    scrape_time = datetime.now().isoformat()
    for quote_card in soup.select("div.quote"):
        quote_text = quote_card.select_one("span.text").get_text(strip=True)
        author = quote_card.select_one("small.author").get_text(strip=True)
        tags = [tag.get_text(strip=True) for tag in quote_card.select("div.tags a.tag")]

        rows.append({
            "quote": quote_text,
            "author": author,
            "tags": tags,
            "scraped_at":scrape_time
        })

    # Volgende pagina
    next_btn = soup.select_one("li.next a")
    url = "http://quotes.toscrape.com" + next_btn["href"] if next_btn else None

# --- Optioneel: check eerste paar quotes ---
df = pd.DataFrame(rows)
print(df.head())

# --- Upload naar Supabase ---
result = supabase.table("quotes").insert(rows).execute()
print(f"✅ Inserted {len(rows)} quotes into Supabase")

# Replace your existing df.to_csv() line with this:
import os

filename = "my_dataset.csv"

if os.path.exists(filename):
    # File already exists → append without writing headers again
    df.to_csv(filename, mode="a", header=False, index=False)
else:
    # First run → create file with headers
    df.to_csv(filename, index=False)

print(f"Appended {len(df)} rows — total file now has historical data")



# Check what your DataFrame looks like right now
print(f"Columns: {list(df.columns)}")
print(f"Data types:\n{df.dtypes}")
print(f"\nFirst 3 rows:")
df.head(3)